import { api } from './auth'

export const getDashboard = (period = '30d') => api(`/dashboard/super-admin?period=${period}`)
export const getFroLiveStatus = () => api('/dashboard/fro-live')
export const getNGOs = () => api('/ngos')
export const getUsers = () => api('/users')
export const getHRs = () => api('/hrs')
export const getWorkers = (params = '') => api(`/workers${params}`)
export const getWorker = (id) => api(`/workers/${id}`)
export const getWorkerAllocations = (id) => api(`/workers/${id}/allocations`)
export const getAttendance = (params = '') => api(`/attendance/all${params}`)
export const getLeaves = () => api('/leaves')
export const getHolidays = () => api('/holidays')
export const getSalarySummary = () => api('/salary/workers-summary')
export const getWorkerSalary = (id) => api(`/salary/worker/${id}/allocations`)
export const getIncentiveMonthlySummary = () => api('/incentive/monthly-summary')
export const getEvents = () => api('/events')
export const getNotices = () => api('/notices')
export const getAchievements = () => api('/achievements')
export const getCauses = (params = '') => api(`/causes${params}`)
export const getDataSources = () => api('/data-sources')
export const getDataImportBatches = () => api('/data-import/batches')
export const getDataImportBatch = (id) => api(`/data-import/batch/${id}`)
export const getAccountsLeads = (status = '') => api(`/accounts/leads${status ? `?status=${status}` : ''}`)
export const getRecruiterLeads = (params = '') => api(`/leads${params}`)
export const getHrVerifiedTickets = () => api('/attendance-corrections/hr-verified')
export const getAllTickets = () => api('/attendance-corrections/all')
export const getPendingCount = () => api('/attendance-corrections/pending-count')
export const approveTicket = (id, admin_remark) => api(`/attendance-corrections/${id}/approve`, { method:'PUT', body:JSON.stringify({ admin_remark }) })
export const rejectTicketSA = (id, remark) => api(`/attendance-corrections/${id}/reject`, { method:'PUT', body:JSON.stringify({ remark }) })
export const getNgoAdminTargets = () => api('/super-admin/ngo-admin-targets')
export const setNgoAdminTarget = (workerId, daily_target) => api(`/super-admin/ngo-admin-targets/${workerId}`, { method:'PUT', body:JSON.stringify({ daily_target }) })
